# Filename: .travis.yml

language: python
cache: pip
python:
- "3.4"
- "3.5"
- "3.6"
install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt
script:
- pylint lendingclub2
- pip install -e . && python -m pytest tests
